blank_issues_enabled: false
contact_links:
  - name: Contributing
    url: https://code.q-ctrl.com/contributing
    about: Guidelines for contributing to Q-CTRL projects.
  - name: Code of Conduct
    url: https://code.q-ctrl.com/code-of-conduct
    about: Code of conduct for contributing to Q-CTRL projects.
  - name: Security
    url: https://github.com/qctrl/.github/blob/master/SECURITY.md
    about: Report a security vulnerability.
  - name: Support
    url: https://github.com/qctrl/.github/blob/master/SUPPORT.md
    about: Get help and support.
  - name: Contact
    url: https://q-ctrl.com/contact
    about: Contact Q-CTRL.
